spring.application.name=NFC-Backend

# Debugging
server.error.whitelabel.enabled=false
spring.jackson.deserialization.FAIL_ON_UNKNOWN_PROPERTIES=false

#the properties for the mySqldriver
spring.datasource.url=jdbc:mysql://srv1823.hstgr.io:3306/u542801010_final
spring.datasource.username=u542801010_final
spring.datasource.password=Gconnect@2028
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#spring.datasource.url=jdbc:mysql://srv1823.hstgr.io:3306/u542801010_test
#spring.datasource.username=u542801010_test
#spring.datasource.password=Gconnectsolutions@2025
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ================== Database Configuration ==================
#spring.datasource.url=jdbc:mysql://localhost:3306/nfc
#spring.datasource.username=root
#spring.datasource.password=Gconnect@2025

# ================== JDBC Driver ==================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ================== JPA & Hibernate ==================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.maxLifetime=1800000
spring.datasource.hikari.connectionTestQuery=SELECT 1
spring.datasource.hikari.validationTimeout=3000


# Redis Cache Configuration
spring.redis.host=localhost
spring.redis.port=6379
spring.cache.type=redis

# Error Handling
server.error.include-message=always
server.error.include-stacktrace=always

#email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mailforalltestings@gmail.com
spring.mail.password=bjgcbmpvdguqvtwv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#thymleaf properties
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

#HTTP Encoding details
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

#secutiry logs
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

#logging configuration
logging.level.root=INFO
logging.level.org.springframework.web=INFO

#validation properties
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
#port number
server.port=9090

#server.servlet.session.cookie.same-site=None
#server.servlet.session.cookie.secure=false